// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.28.1
// source: protos/product.proto

package product_proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ProductProto_GetProduct_FullMethodName = "/product_proto.ProductProto/GetProduct"
)

// ProductProtoClient is the client API for ProductProto service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ProductProtoClient interface {
	GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error)
}

type productProtoClient struct {
	cc grpc.ClientConnInterface
}

func NewProductProtoClient(cc grpc.ClientConnInterface) ProductProtoClient {
	return &productProtoClient{cc}
}

func (c *productProtoClient) GetProduct(ctx context.Context, in *GetProductRequest, opts ...grpc.CallOption) (*GetProductResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetProductResponse)
	err := c.cc.Invoke(ctx, ProductProto_GetProduct_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ProductProtoServer is the server API for ProductProto service.
// All implementations must embed UnimplementedProductProtoServer
// for forward compatibility.
type ProductProtoServer interface {
	GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error)
	mustEmbedUnimplementedProductProtoServer()
}

// UnimplementedProductProtoServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedProductProtoServer struct{}

func (UnimplementedProductProtoServer) GetProduct(context.Context, *GetProductRequest) (*GetProductResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetProduct not implemented")
}
func (UnimplementedProductProtoServer) mustEmbedUnimplementedProductProtoServer() {}
func (UnimplementedProductProtoServer) testEmbeddedByValue()                      {}

// UnsafeProductProtoServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ProductProtoServer will
// result in compilation errors.
type UnsafeProductProtoServer interface {
	mustEmbedUnimplementedProductProtoServer()
}

func RegisterProductProtoServer(s grpc.ServiceRegistrar, srv ProductProtoServer) {
	// If the following call pancis, it indicates UnimplementedProductProtoServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ProductProto_ServiceDesc, srv)
}

func _ProductProto_GetProduct_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetProductRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ProductProtoServer).GetProduct(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ProductProto_GetProduct_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ProductProtoServer).GetProduct(ctx, req.(*GetProductRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ProductProto_ServiceDesc is the grpc.ServiceDesc for ProductProto service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ProductProto_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "product_proto.ProductProto",
	HandlerType: (*ProductProtoServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetProduct",
			Handler:    _ProductProto_GetProduct_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/product.proto",
}
