// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package sqlc

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Product struct {
	ID            int32
	CreatedAt     pgtype.Timestamp
	UpdatedAt     pgtype.Timestamp
	DeletedAt     pgtype.Timestamp
	Uuid          pgtype.UUID
	PromotionID   int32
	Sku           string
	Name          string
	PurchaseLimit int32
}

type ProductVariant struct {
	ID                   int32
	CreatedAt            pgtype.Timestamp
	UpdatedAt            pgtype.Timestamp
	DeletedAt            pgtype.Timestamp
	Uuid                 pgtype.UUID
	ProductID            int32
	Sku                  string
	Name                 string
	DiscountedPrice      float64
	DiscountedPercentage float64
	StockLimit           int32
	IsActive             bool
}

type Promotion struct {
	ID                int32
	CreatedAt         pgtype.Timestamp
	UpdatedAt         pgtype.Timestamp
	DeletedAt         pgtype.Timestamp
	Uuid              pgtype.UUID
	Name              string
	PromotionType     string
	Code              string
	StartTime         pgtype.Timestamp
	EndTime           pgtype.Timestamp
	ShopID            string
	UsageQuantity     int32
	UsageLimitPerUser int32
}
