begin;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create table if not exists promotions (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null,

    name varchar(255) not null,
    promotion_type varchar(50) not null,
    code varchar(255) not null,
    start_time timestamp not null,
    end_time timestamp not null,
    shop_id varchar(255) not null,
    usage_quantity integer not null,
    usage_limit_per_user integer not null
);


create table if not exists products (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null,

    promotion_id uuid not null,
    sku varchar(255) not null,
    name varchar(255) not null,
    purchase_limit integer not null
);



create table if not exists product_variants (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null,
    
    promotion_id uuid not null,
    product_id uuid not null,
    sku varchar(255) not null,
    name varchar(255) not null,
    discounted_price float not null,
    discounted_percentage float not null,
    stock_limit integer not null,
    is_active boolean not null
);

commit;