begin;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

create schema if not exists promotion;

create table if not exists promotion.promotions (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null default uuid_generate_v4(),

    name varchar(255) not null,
    promotion_type varchar(50) not null,
    code varchar(255) not null,
    start_time timestamp not null,
    end_time timestamp not null,
    shop_id varchar(255) not null,
    usage_quantity integer not null,
    usage_limit_per_user integer not null
);


create table if not exists promotion.products (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null default uuid_generate_v4(),

    promotion_id uuid not null,
    sku varchar(255) not null,
    name varchar(255) not null,
    purchase_limit integer not null
);



create table if not exists promotion.product_variants (
    id integer not null generated by default as identity primary key,
    created_at timestamp not null default current_timestamp,
    updated_at timestamp not null default current_timestamp,
    deleted_at timestamp default null,
    uuid uuid not null default uuid_generate_v4(),
    
    promotion_id uuid not null,
    product_id uuid not null,
    sku varchar(255) not null,
    name varchar(255) not null,
    discounted_price float not null,
    discounted_percentage float not null,
    stock_limit integer not null,
    is_active boolean not null
);


-- create index if not exists idx_promotions_id on promotion.promotions (id, deleted_at);
-- create index if not exists idx_promotions_uuid on promotion.promotions (uuid, deleted_at);
-- create index if not exists idx_promotions_shop_id on promotion.promotions (id, deleted_at, shop_id);

-- create index if not exists idx_products on promotion.products (promotion_id);

-- create index if not exists idx_variants on promotion.product_variants (product_id);

commit;